sudo: false
addons:
  apt:
    packages:
    - nginx
before_install:
  - npm install -g jshint bower
install:
  - bower install
before_script:
  - cat test/travis.conf | envsubst > test/travis-envsubst.conf
  - nginx -c `pwd`/test/travis-envsubst.conf
script:
  - phantomjs test/run-jasmine.js http://localhost:9000/test/
  - jshint js
